#preload = ~/.local/share/wallpaper
#wallpaper = eDP-1,~/.local/share/wallpaper
#wallpaper = HDMI-A-1,~/.local/share/wallpaper

wallpaper {
	monitor = eDP-1
	path = ~/.local/share/wallpaper
	fit_mode = cover
}
