#windowrule = workspace special:telegram, class:org.telegram.desktop
#windowrule = pseudo, class:blueberry.py
#windowrule = pseudo, class:org.pulseaudio.pavucontrol
#windowrule = size 40% 60%, class:blueberry.py
#windowrule = size 40% 60%, class:org.pulseaudio.pavucontrol
#windowrule = suppressevent maximize, class:.*
#windowrule = float, class:org.gnome.Decibels
windowrule = workspace special:telegram, match:class org.telegram.desktop
windowrule = pseudo on, match:class blueberry.py
windowrule = pseudo on, match:class org.pulseaudio.pavucontrol
#windowrule = size 40% 60%, class:blueberry.py
#windowrule = size 40% 60%, class:org.pulseaudio.pavucontrol
#windowrule = suppressevent maximize, class:.*
windowrule = float on, match:class org.gnome.Decibels
windowrule = border_size 0, match:workspace w[tv1]
