windowrule = workspace special:telegram, match:class org.telegram.desktop
windowrule = pseudo on, match:class blueberry.py
windowrule = pseudo on, match:class org.pulseaudio.pavucontrol
windowrule = float on, match:class org.gnome.Decibels
windowrule = border_size 0, match:workspace w[tv1]
